---
title: "git basics"
author: "vgranda"
date: "2023-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

`git` is a version control software, not the only one, but one of the most
widely used. But, what is *version control*?  
As the [git book](https://git-scm.com/book/en/v2) explains, version control
systems allow to record the changes a file or a set of files have been through,
allowing to revert files to a previous state, compare changes over time...  
Version control systems, and `git` in particular, are designed with
collaborative development in mind (a team working in the same codebase), but it
doesn't mean it can't be used in *solo* projects, and in fact, is recommended.

  > **Important!! `git` is not a backup system**. Is not intended to be a backup
  system. Think of it more as a time machine for your code, but you should have
  backup copies besides any version control system.

## How `git` works

Think of `git` as a series of snapshots of the files. Every time we `commit`
some changes, an image of the state of the files is stored. This allows to
follow the development of the project (how things changed), but more
importantly, it allows to go back to any point in the `commit` history.  

Let's say that you are performing some analyses in your R project and something
is not working as intended. You try to fix it, but at the end you have made so
many changes to the analysis code that is impossible to revert to the state in
which everything worked again. With `git` you have the history of changes
stored, you can see differences in files you modified, and when you modified it,
and also you can go back easily to any point in that history.

